name: Build-Yusuf-Menu
on:
  workflow_dispatch:
jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup-Theos
        run: |
          git clone --recursive https://github.com/theos/theos.git ~/theos
          curl -LO https://github.com/theos/sdks/archive/master.zip
          unzip master.zip -d ~/theos/sdks
          mv ~/theos/sdks/sdks-master/* ~/theos/sdks/
          echo "THEOS=~/theos" >> $GITHUB_ENV
      - name: Build-Package
        run: |
          export THEOS=~/theos
          make package FINALPACKAGE=1
      - name: Upload-Artifact
        uses: actions/upload-artifact@v4
        with:
          name: Yusuf-Mod-Menu
          path: packages/*.deb
